travis:
  secure:
    BINSTAR_TOKEN: iiSg6O2bmfAMerIxdk2dj6Y96yKa9zu2B7bqkvZAg4wsCdJ2ulLqCFu/GR+UGr0Z3lE0XB/cDwWROd5nNAYtd+d0NwjHdf03hwkNgzdc9Gl09eehz9ND999lLPqgbKjTY/5VtTe2JThtzmXYMNpHweMdkKKSjIeas46spREc6CvKuVVeHZDHQA8V6NeeNiW8GLYi+ez2HKl9iw4VYZGyZlIg+LZYI5wSt6DuU+cd07gf+5OxlgUyszFpP15O4dMnixurMguL1O/OUqQwBgyHZat+orlBzzodBJNltrdkf05nn0w+/RbRKYn8yJnaIIEj4ZDcpziHjN8HQaB4eHAQxhvLGPRTY99sRINqZnzFIOhRqZusUyMhiqhe1KX16grCVZIwH+pTewu30s0/NoKrYBWnQagoCCIkX0jpt9GwF/p72yAzEhPS58yKRHY7dksRrb6crXWxnpaDSxNB+QqSMcr84rqYRtN0dPkFzRxFbc8SJmpTPBSz8guuseihe9dGSWV1SUpapa8ScjpyY6Xl4Ugkfe+herOaQLal7fCc5DSBHAV8Ez7KSfgDgwGR8q8n2TfaYCAbtue94Fo9NPAd9LkX+kIagfNZfI339bX6vUdyL9Jn2kpEZifG1sowqqe3hgIGITv0gRh0IQe8CeC0snDJQir/L/ITmH5uhVPyp3A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
